// 词库 — 210个单词，6个单元（三年级下学期）
export const WORDS = [
  // Unit 1 (27)
  { id: "feeling", word: "feeling", meaning: "感觉", phonetic: "/ˈfiːlɪŋ/", unit: 1, grade: 3, semester: 2 },
  { id: "tired", word: "tired", meaning: "疲惫的", phonetic: "/ˈtaɪəd/", unit: 1, grade: 3, semester: 2 },
  { id: "sad", word: "sad", meaning: "难过的", phonetic: "/sæd/", unit: 1, grade: 3, semester: 2 },
  { id: "angry", word: "angry", meaning: "生气的", phonetic: "/ˈæŋɡri/", unit: 1, grade: 3, semester: 2 },
  { id: "scared", word: "scared", meaning: "害怕的", phonetic: "/skeəd/", unit: 1, grade: 3, semester: 2 },
  { id: "cry", word: "cry", meaning: "哭", phonetic: "/kraɪ/", unit: 1, grade: 3, semester: 2 },
  { id: "laugh", word: "laugh", meaning: "笑", phonetic: "/lɑːf/", unit: 1, grade: 3, semester: 2 },
  { id: "stamp", word: "stamp", meaning: "跺(脚)", phonetic: "/stæmp/", unit: 1, grade: 3, semester: 2 },
  { id: "sleep", word: "sleep", meaning: "睡觉", phonetic: "/sliːp/", unit: 1, grade: 3, semester: 2 },
  { id: "new", word: "new", meaning: "新的", phonetic: "/njuː/", unit: 1, grade: 3, semester: 2 },
  { id: "game", word: "game", meaning: "游戏", phonetic: "/ɡeɪm/", unit: 1, grade: 3, semester: 2 },
  { id: "excited", word: "excited", meaning: "兴奋的", phonetic: "/ɪkˈsaɪtɪd/", unit: 1, grade: 3, semester: 2 },
  { id: "sorry", word: "sorry", meaning: "对不起", phonetic: "/ˈsɒri/", unit: 1, grade: 3, semester: 2 },
  { id: "like", word: "like", meaning: "喜欢", phonetic: "/laɪk/", unit: 1, grade: 3, semester: 2 },
  { id: "but", word: "but", meaning: "但是", phonetic: "/bʌt/", unit: 1, grade: 3, semester: 2 },
  { id: "unhappy", word: "unhappy", meaning: "不开心的", phonetic: "/ʌnˈhæpi/", unit: 1, grade: 3, semester: 2 },
  { id: "worried", word: "worried", meaning: "担心的", phonetic: "/ˈwʌrid/", unit: 1, grade: 3, semester: 2 },
  { id: "not", word: "not", meaning: "不;不是", phonetic: "/nɒt/", unit: 1, grade: 3, semester: 2 },
  { id: "feel", word: "feel", meaning: "感觉到", phonetic: "/fiːl/", unit: 1, grade: 3, semester: 2 },
  { id: "find", word: "find", meaning: "找到", phonetic: "/faɪnd/", unit: 1, grade: 3, semester: 2 },
  { id: "doll", word: "doll", meaning: "玩偶", phonetic: "/dɒl/", unit: 1, grade: 3, semester: 2 },
  { id: "football", word: "football", meaning: "足球", phonetic: "/ˈfʊtbɔːl/", unit: 1, grade: 3, semester: 2 },
  { id: "eat", word: "eat", meaning: "吃", phonetic: "/iːt/", unit: 1, grade: 3, semester: 2 },
  { id: "his", word: "his", meaning: "他的", phonetic: "/hɪz/", unit: 1, grade: 3, semester: 2 },
  { id: "cake", word: "cake", meaning: "蛋糕", phonetic: "/keɪk/", unit: 1, grade: 3, semester: 2 },
  { id: "big", word: "big", meaning: "大的", phonetic: "/bɪɡ/", unit: 1, grade: 3, semester: 2 },
  { id: "mouse", word: "mouse", meaning: "老鼠", phonetic: "/maʊs/", unit: 1, grade: 3, semester: 2 },

  // Unit 2 (30)
  { id: "know", word: "know", meaning: "了解", phonetic: "/nəʊ/", unit: 2 },
  { id: "body", word: "body", meaning: "身体", phonetic: "/ˈbɒdi/", unit: 2 },
  { id: "rock", word: "rock", meaning: "摇滚乐", phonetic: "/rɒk/", unit: 2 },
  { id: "song", word: "song", meaning: "歌曲", phonetic: "/sɒŋ/", unit: 2 },
  { id: "touch", word: "touch", meaning: "触摸", phonetic: "/tʌtʃ/", unit: 2 },
  { id: "head", word: "head", meaning: "头", phonetic: "/hed/", unit: 2 },
  { id: "eye", word: "eye", meaning: "眼睛", phonetic: "/aɪ/", unit: 2 },
  { id: "hair", word: "hair", meaning: "头发", phonetic: "/heə/", unit: 2 },
  { id: "short", word: "short", meaning: "短的", phonetic: "/ʃɔːt/", unit: 2 },
  { id: "small", word: "small", meaning: "小的", phonetic: "/smɔːl/", unit: 2 },
  { id: "ear", word: "ear", meaning: "耳朵", phonetic: "/ɪə/", unit: 2 },
  { id: "wave", word: "wave", meaning: "摆动", phonetic: "/weɪv/", unit: 2 },
  { id: "leg", word: "leg", meaning: "腿", phonetic: "/leɡ/", unit: 2 },
  { id: "foot", word: "foot", meaning: "脚", phonetic: "/fʊt/", unit: 2 },
  { id: "nose", word: "nose", meaning: "鼻子", phonetic: "/nəʊz/", unit: 2 },
  { id: "face", word: "face", meaning: "脸", phonetic: "/feɪs/", unit: 2 },
  { id: "arm", word: "arm", meaning: "手臂", phonetic: "/ɑːm/", unit: 2 },
  { id: "hand", word: "hand", meaning: "手", phonetic: "/hænd/", unit: 2 },
  { id: "mouth", word: "mouth", meaning: "嘴", phonetic: "/maʊθ/", unit: 2 },
  { id: "tooth", word: "tooth", meaning: "牙", phonetic: "/tuːθ/", unit: 2 },
  { id: "prize", word: "prize", meaning: "奖品", phonetic: "/praɪz/", unit: 2 },
  { id: "bike", word: "bike", meaning: "自行车", phonetic: "/baɪk/", unit: 2 },
  { id: "race", word: "race", meaning: "竞赛", phonetic: "/reɪs/", unit: 2 },
  { id: "stretch", word: "stretch", meaning: "伸展", phonetic: "/stretʃ/", unit: 2 },
  { id: "shake", word: "shake", meaning: "摇动", phonetic: "/ʃeɪk/", unit: 2 },
  { id: "here", word: "here", meaning: "在这里", phonetic: "/hɪə/", unit: 2 },
  { id: "Mr", word: "Mr", meaning: "先生", phonetic: "/ˈmɪstə/", unit: 2 },
  { id: "back", word: "back", meaning: "回到原处", phonetic: "/bæk/", unit: 2 },
  { id: "worry", word: "worry", meaning: "担心", phonetic: "/ˈwʌri/", unit: 2 },
  { id: "robot", word: "robot", meaning: "机器人", phonetic: "/ˈrəʊbɒt/", unit: 2 },

  // Unit 3 (41)
  { id: "so", word: "so", meaning: "这么", phonetic: "/səʊ/", unit: 3 },
  { id: "cool", word: "cool", meaning: "酷的", phonetic: "/kuːl/", unit: 3 },
  { id: "clothes", word: "clothes", meaning: "衣服", phonetic: "/kləʊðz/", unit: 3 },
  { id: "wear", word: "wear", meaning: "穿", phonetic: "/weə/", unit: 3 },
  { id: "cap", word: "cap", meaning: "帽子", phonetic: "/kæp/", unit: 3 },
  { id: "T-shirt", word: "T-shirt", meaning: "T恤", phonetic: "/ˈtiːʃɜːt/", unit: 3 },
  { id: "trousers", word: "trousers", meaning: "裤子", phonetic: "/ˈtraʊzəz/", unit: 3 },
  { id: "sock", word: "sock", meaning: "袜子", phonetic: "/sɒk/", unit: 3 },
  { id: "shiny", word: "shiny", meaning: "有光泽的", phonetic: "/ˈʃaɪni/", unit: 3 },
  { id: "shoe", word: "shoe", meaning: "鞋", phonetic: "/ʃuː/", unit: 3 },
  { id: "dress", word: "dress", meaning: "连衣裙", phonetic: "/dres/", unit: 3 },
  { id: "sweater", word: "sweater", meaning: "毛线衣", phonetic: "/ˈswetə/", unit: 3 },
  { id: "skirt", word: "skirt", meaning: "半身裙", phonetic: "/skɜːt/", unit: 3 },
  { id: "shirt", word: "shirt", meaning: "衬衫", phonetic: "/ʃɜːt/", unit: 3 },
  { id: "coat", word: "coat", meaning: "外套", phonetic: "/kəʊt/", unit: 3 },
  { id: "shorts", word: "shorts", meaning: "短裤", phonetic: "/ʃɔːts/", unit: 3 },
  { id: "king", word: "king", meaning: "国王", phonetic: "/kɪŋ/", unit: 3 },
  { id: "want", word: "want", meaning: "想要", phonetic: "/wɒnt/", unit: 3 },
  { id: "beautiful", word: "beautiful", meaning: "美丽的", phonetic: "/ˈbjuːtɪfʊl/", unit: 3 },
  { id: "make", word: "make", meaning: "做", phonetic: "/meɪk/", unit: 3 },
  { id: "magic", word: "magic", meaning: "神奇的", phonetic: "/ˈmædʒɪk/", unit: 3 },
  { id: "people", word: "people", meaning: "人", phonetic: "/ˈpiːpəl/", unit: 3 },
  { id: "them", word: "them", meaning: "它们", phonetic: "/ðem/", unit: 3 },
  { id: "after", word: "after", meaning: "在……后", phonetic: "/ˈɑːftə/", unit: 3 },
  { id: "month", word: "month", meaning: "月", phonetic: "/mʌnθ/", unit: 3 },
  { id: "try", word: "try", meaning: "试", phonetic: "/traɪ/", unit: 3 },
  { id: "why", word: "why", meaning: "为什么", phonetic: "/waɪ/", unit: 3 },
  { id: "wonderful", word: "wonderful", meaning: "令人惊叹的", phonetic: "/ˈwʌndəfʊl/", unit: 3 },
  { id: "most", word: "most", meaning: "最", phonetic: "/məʊst/", unit: 3 },
  { id: "any", word: "any", meaning: "其他的", phonetic: "/ˈeni/", unit: 3 },
  { id: "or", word: "or", meaning: "或", phonetic: "/ɔː/", unit: 3 },
  { id: "fox", word: "fox", meaning: "狐狸", phonetic: "/fɒks/", unit: 3 },
  { id: "monkey", word: "monkey", meaning: "猴子", phonetic: "/ˈmʌŋki/", unit: 3 },
  { id: "tell", word: "tell", meaning: "告诉", phonetic: "/tel/", unit: 3 },
  { id: "truth", word: "truth", meaning: "真相", phonetic: "/truːθ/", unit: 3 },
  { id: "wash", word: "wash", meaning: "洗", phonetic: "/wɒʃ/", unit: 3 },
  { id: "hang", word: "hang", meaning: "悬挂", phonetic: "/hæŋ/", unit: 3 },
  { id: "hat", word: "hat", meaning: "帽子", phonetic: "/hæt/", unit: 3 },
  { id: "jeans", word: "jeans", meaning: "牛仔裤", phonetic: "/dʒiːnz/", unit: 3 },
  { id: "boot", word: "boot", meaning: "靴子", phonetic: "/buːt/", unit: 3 },
  { id: "robe", word: "robe", meaning: "长袍", phonetic: "/rəʊb/", unit: 3 },

  // Unit 4 (42)
  { id: "rain", word: "rain", meaning: "雨", phonetic: "/reɪn/", unit: 4 },
  { id: "sun", word: "sun", meaning: "阳光", phonetic: "/sʌn/", unit: 4 },
  { id: "rainy", word: "rainy", meaning: "多雨的", phonetic: "/ˈreɪni/", unit: 4 },
  { id: "run", word: "run", meaning: "跑", phonetic: "/rʌn/", unit: 4 },
  { id: "windy", word: "windy", meaning: "多风的", phonetic: "/ˈwɪndi/", unit: 4 },
  { id: "fly", word: "fly", meaning: "放飞", phonetic: "/flaɪ/", unit: 4 },
  { id: "kite", word: "kite", meaning: "风筝", phonetic: "/kaɪt/", unit: 4 },
  { id: "park", word: "park", meaning: "公园", phonetic: "/pɑːk/", unit: 4 },
  { id: "hot", word: "hot", meaning: "炎热的", phonetic: "/hɒt/", unit: 4 },
  { id: "sunny", word: "sunny", meaning: "阳光充足的", phonetic: "/ˈsʌni/", unit: 4 },
  { id: "swim", word: "swim", meaning: "游泳", phonetic: "/swɪm/", unit: 4 },
  { id: "water", word: "water", meaning: "水", phonetic: "/ˈwɔːtə/", unit: 4 },
  { id: "cold", word: "cold", meaning: "寒冷的", phonetic: "/kəʊld/", unit: 4 },
  { id: "snowy", word: "snowy", meaning: "多雪的", phonetic: "/ˈsnəʊi/", unit: 4 },
  { id: "throw", word: "throw", meaning: "投;扔", phonetic: "/θrəʊ/", unit: 4 },
  { id: "snowball", word: "snowball", meaning: "雪球", phonetic: "/ˈsnəʊbɔːl/", unit: 4 },
  { id: "umbrella", word: "umbrella", meaning: "雨伞", phonetic: "/ʌmˈbrelə/", unit: 4 },
  { id: "warm", word: "warm", meaning: "保暖的", phonetic: "/wɔːm/", unit: 4 },
  { id: "music", word: "music", meaning: "音乐", phonetic: "/ˈmjuːzɪk/", unit: 4 },
  { id: "weather", word: "weather", meaning: "天气", phonetic: "/ˈweðə/", unit: 4 },
  { id: "bookshop", word: "bookshop", meaning: "书店", phonetic: "/ˈbʊkʃɒp/", unit: 4 },
  { id: "wait", word: "wait", meaning: "等", phonetic: "/weɪt/", unit: 4 },
  { id: "wet", word: "wet", meaning: "湿的", phonetic: "/wet/", unit: 4 },
  { id: "again", word: "again", meaning: "又", phonetic: "/əˈɡen/", unit: 4 },
  { id: "dry", word: "dry", meaning: "干燥的", phonetic: "/draɪ/", unit: 4 },
  { id: "sell", word: "sell", meaning: "卖", phonetic: "/sel/", unit: 4 },
  { id: "these", word: "these", meaning: "这些", phonetic: "/ðiːz/", unit: 4 },
  { id: "idea", word: "idea", meaning: "主意", phonetic: "/aɪˈdɪə/", unit: 4 },
  { id: "club", word: "club", meaning: "俱乐部", phonetic: "/klʌb/", unit: 4 },
  { id: "welcome", word: "welcome", meaning: "欢迎", phonetic: "/ˈwelkəm/", unit: 4 },
  { id: "stand", word: "stand", meaning: "站立", phonetic: "/stænd/", unit: 4 },
  { id: "board", word: "board", meaning: "公告牌", phonetic: "/bɔːd/", unit: 4 },
  { id: "walk", word: "walk", meaning: "走", phonetic: "/wɔːk/", unit: 4 },
  { id: "carefully", word: "carefully", meaning: "小心地", phonetic: "/ˈkeəfəli/", unit: 4 },
  { id: "tree", word: "tree", meaning: "树", phonetic: "/triː/", unit: 4 },
  { id: "spring", word: "spring", meaning: "春天", phonetic: "/sprɪŋ/", unit: 4 },
  { id: "summer", word: "summer", meaning: "夏天", phonetic: "/ˈsʌmə/", unit: 4 },
  { id: "autumn", word: "autumn", meaning: "秋天", phonetic: "/ˈɔːtəm/", unit: 4 },
  { id: "winter", word: "winter", meaning: "冬天", phonetic: "/ˈwɪntə/", unit: 4 },
  { id: "season", word: "season", meaning: "季节", phonetic: "/ˈsiːzən/", unit: 4 },
  { id: "drawing", word: "drawing", meaning: "图画", phonetic: "/ˈdrɔːɪŋ/", unit: 4 },
  { id: "cloudy", word: "cloudy", meaning: "多云的", phonetic: "/ˈklaʊdi/", unit: 4 },

  // Unit 5 (24)
  { id: "week", word: "week", meaning: "星期", phonetic: "/wiːk/", unit: 5 },
  { id: "Monday", word: "Monday", meaning: "星期一", phonetic: "/ˈmʌndeɪ/", unit: 5 },
  { id: "Tuesday", word: "Tuesday", meaning: "星期二", phonetic: "/ˈtjuːzdeɪ/", unit: 5 },
  { id: "Wednesday", word: "Wednesday", meaning: "星期三", phonetic: "/ˈwenzdeɪ/", unit: 5 },
  { id: "Thursday", word: "Thursday", meaning: "星期四", phonetic: "/ˈθɜːzdeɪ/", unit: 5 },
  { id: "Friday", word: "Friday", meaning: "星期五", phonetic: "/ˈfraɪdeɪ/", unit: 5 },
  { id: "Saturday", word: "Saturday", meaning: "星期六", phonetic: "/ˈsætədeɪ/", unit: 5 },
  { id: "Sunday", word: "Sunday", meaning: "星期日", phonetic: "/ˈsʌndeɪ/", unit: 5 },
  { id: "before", word: "before", meaning: "在……以前", phonetic: "/bɪˈfɔː/", unit: 5 },
  { id: "room", word: "room", meaning: "房间", phonetic: "/ruːm/", unit: 5 },
  { id: "close", word: "close", meaning: "关;闭合", phonetic: "/kləʊz/", unit: 5 },
  { id: "much", word: "much", meaning: "非常", phonetic: "/mʌtʃ/", unit: 5 },
  { id: "rabbit", word: "rabbit", meaning: "兔", phonetic: "/ˈræbɪt/", unit: 5 },
  { id: "cat", word: "cat", meaning: "猫", phonetic: "/kæt/", unit: 5 },
  { id: "fish", word: "fish", meaning: "鱼", phonetic: "/fɪʃ/", unit: 5 },
  { id: "busy", word: "busy", meaning: "忙碌的", phonetic: "/ˈbɪzi/", unit: 5 },
  { id: "every", word: "every", meaning: "每一个", phonetic: "/ˈevri/", unit: 5 },
  { id: "cooking", word: "cooking", meaning: "做饭", phonetic: "/ˈkʊkɪŋ/", unit: 5 },
  { id: "cook", word: "cook", meaning: "烹调", phonetic: "/kʊk/", unit: 5 },
  { id: "Chinese", word: "Chinese", meaning: "中国的", phonetic: "/ˌtʃaɪˈniːz/", unit: 5 },
  { id: "chess", word: "chess", meaning: "国际象棋", phonetic: "/tʃes/", unit: 5 },
  { id: "study", word: "study", meaning: "学习", phonetic: "/ˈstʌdi/", unit: 5 },
  { id: "basketball", word: "basketball", meaning: "篮球", phonetic: "/ˈbɑːskɪtbɔːl/", unit: 5 },
  { id: "activity", word: "activity", meaning: "活动", phonetic: "/ækˈtɪvɪti/", unit: 5 },

  // Unit 6 (46)
  { id: "apple", word: "apple", meaning: "苹果", phonetic: "/ˈæpəl/", unit: 6 },
  { id: "egg", word: "egg", meaning: "鸡蛋", phonetic: "/eɡ/", unit: 6 },
  { id: "bread", word: "bread", meaning: "面包", phonetic: "/bred/", unit: 6 },
  { id: "milk", word: "milk", meaning: "奶", phonetic: "/mɪlk/", unit: 6 },
  { id: "rice", word: "rice", meaning: "米饭", phonetic: "/raɪs/", unit: 6 },
  { id: "tomato", word: "tomato", meaning: "西红柿", phonetic: "/təˈmɑːtəʊ/", unit: 6 },
  { id: "juice", word: "juice", meaning: "果汁", phonetic: "/dʒuːs/", unit: 6 },
  { id: "candy", word: "candy", meaning: "糖果", phonetic: "/ˈkændi/", unit: 6 },
  { id: "ice_cream", word: "ice cream", meaning: "冰激凌", phonetic: "/ˌaɪs ˈkriːm/", unit: 6 },
  { id: "chicken", word: "chicken", meaning: "鸡肉", phonetic: "/ˈtʃɪkɪn/", unit: 6 },
  { id: "noodles", word: "noodles", meaning: "面条", phonetic: "/ˈnuːdəlz/", unit: 6 },
  { id: "banana", word: "banana", meaning: "香蕉", phonetic: "/bəˈnɑːnə/", unit: 6 },
  { id: "dinner", word: "dinner", meaning: "正餐", phonetic: "/ˈdɪnə/", unit: 6 },
  { id: "parent", word: "parent", meaning: "父母", phonetic: "/ˈpeərənt/", unit: 6 },
  { id: "dish", word: "dish", meaning: "一道菜", phonetic: "/dɪʃ/", unit: 6 },
  { id: "meat", word: "meat", meaning: "肉", phonetic: "/miːt/", unit: 6 },
  { id: "mushroom", word: "mushroom", meaning: "蘑菇", phonetic: "/ˈmʌʃruːm/", unit: 6 },
  { id: "potato", word: "potato", meaning: "土豆", phonetic: "/pəˈteɪtəʊ/", unit: 6 },
  { id: "eggplant", word: "eggplant", meaning: "茄子", phonetic: "/ˈeɡplɑːnt/", unit: 6 },
  { id: "food", word: "food", meaning: "食物", phonetic: "/fuːd/", unit: 6 },
  { id: "amazing", word: "amazing", meaning: "惊人的", phonetic: "/əˈmeɪzɪŋ/", unit: 6 },
  { id: "say", word: "say", meaning: "说", phonetic: "/seɪ/", unit: 6 },
  { id: "grape", word: "grape", meaning: "葡萄", phonetic: "/ɡreɪp/", unit: 6 },
  { id: "vegetable", word: "vegetable", meaning: "蔬菜", phonetic: "/ˈvedʒtəbəl/", unit: 6 },
  { id: "soup", word: "soup", meaning: "汤", phonetic: "/suːp/", unit: 6 },
  { id: "drink", word: "drink", meaning: "饮料", phonetic: "/drɪŋk/", unit: 6 },
  { id: "need", word: "need", meaning: "需要", phonetic: "/niːd/", unit: 6 },
  { id: "oil", word: "oil", meaning: "油", phonetic: "/ɔɪl/", unit: 6 },
  { id: "salt", word: "salt", meaning: "盐", phonetic: "/sɔːlt/", unit: 6 },
  { id: "beat", word: "beat", meaning: "搅拌", phonetic: "/biːt/", unit: 6 },
  { id: "dragon", word: "dragon", meaning: "龙", phonetic: "/ˈdræɡən/", unit: 6 },
  { id: "point", word: "point", meaning: "指", phonetic: "/pɔɪnt/", unit: 6 },
  { id: "house", word: "house", meaning: "房子", phonetic: "/haʊs/", unit: 6 },
  { id: "lot", word: "lot", meaning: "许多", phonetic: "/lɒt/", unit: 6 },
  { id: "cup", word: "cup", meaning: "杯子", phonetic: "/kʌp/", unit: 6 },
  { id: "real", word: "real", meaning: "真的", phonetic: "/rɪəl/", unit: 6 },
  { id: "picnic", word: "picnic", meaning: "野餐", phonetic: "/ˈpɪknɪk/", unit: 6 },
  { id: "sit", word: "sit", meaning: "坐", phonetic: "/sɪt/", unit: 6 },
  { id: "yummy", word: "yummy", meaning: "很好吃的", phonetic: "/ˈjʌmi/", unit: 6 },
  { id: "bottle", word: "bottle", meaning: "瓶子", phonetic: "/ˈbɒtəl/", unit: 6 },
  { id: "box", word: "box", meaning: "盒", phonetic: "/bɒks/", unit: 6 },
  { id: "peel", word: "peel", meaning: "外皮", phonetic: "/piːl/", unit: 6 },
  { id: "sure", word: "sure", meaning: "当然", phonetic: "/ʃʊə/", unit: 6 },
  { id: "minute", word: "minute", meaning: "分钟", phonetic: "/ˈmɪnɪt/", unit: 6 },
  { id: "sky", word: "sky", meaning: "天", phonetic: "/skaɪ/", unit: 6 },
  { id: "grass", word: "grass", meaning: "草", phonetic: "/ɡrɑːs/", unit: 6 },
]

// 辅助函数
export function getWordsByUnit(unit, grade = 3, semester = 2) {
  return WORDS.filter((w) => w.unit === unit && (w.grade || 3) === grade && (w.semester || 2) === semester)
}

export function getWordsByGradeSemester(grade, semester) {
  return WORDS.filter((w) => (w.grade || 3) === grade && (w.semester || 2) === semester)
}

export function getWordById(id) {
  return WORDS.find((w) => w.id === id) || null
}


