// 词库 — 407个单词（三年级上册197 + 下册210）
export const WORDS = [
  // ==================== 三年级上册（semester: 1）====================

  // Welcome unit (27)
  { id: "let", word: "let", meaning: "让", phonetic: "/let/", unit: 0, grade: 3, semester: 1 },
  { id: "begin", word: "begin", meaning: "开始", phonetic: "/bɪˈɡɪn/", unit: 0, grade: 3, semester: 1 },
  { id: "join", word: "join", meaning: "加入", phonetic: "/dʒɔɪn/", unit: 0, grade: 3, semester: 1 },
  { id: "in", word: "in", meaning: "在……中", phonetic: "/ɪn/", unit: 0, grade: 3, semester: 1 },
  { id: "english", word: "English", meaning: "英语", phonetic: "/ˈɪŋɡlɪʃ/", unit: 0, grade: 3, semester: 1 },
  { id: "be", word: "be", meaning: "是", phonetic: "/biː/", unit: 0, grade: 3, semester: 1 },
  { id: "easy", word: "easy", meaning: "容易的", phonetic: "/ˈiːzi/", unit: 0, grade: 3, semester: 1 },
  { id: "come", word: "come", meaning: "来", phonetic: "/kʌm/", unit: 0, grade: 3, semester: 1 },
  { id: "and", word: "and", meaning: "和", phonetic: "/ænd/", unit: 0, grade: 3, semester: 1 },
  { id: "you", word: "you", meaning: "你；你们", phonetic: "/juː/", unit: 0, grade: 3, semester: 1 },
  { id: "ready", word: "ready", meaning: "准备好的", phonetic: "/ˈredi/", unit: 0, grade: 3, semester: 1 },
  { id: "kid", word: "kid", meaning: "小孩，儿童", phonetic: "/kɪd/", unit: 0, grade: 3, semester: 1 },
  { id: "yeah", word: "yeah", meaning: "是", phonetic: "/jeə/", unit: 0, grade: 3, semester: 1 },
  { id: "ok", word: "OK", meaning: "行，可以", phonetic: "/ˌəʊˈkeɪ/", unit: 0, grade: 3, semester: 1 },
  { id: "listen", word: "listen", meaning: "听", phonetic: "/ˈlɪsən/", unit: 0, grade: 3, semester: 1 },
  { id: "sing", word: "sing", meaning: "唱", phonetic: "/sɪŋ/", unit: 0, grade: 3, semester: 1 },
  { id: "mime", word: "mime", meaning: "比画着表达", phonetic: "/maɪm/", unit: 0, grade: 3, semester: 1 },
  { id: "speak", word: "speak", meaning: "说话", phonetic: "/spiːk/", unit: 0, grade: 3, semester: 1 },
  { id: "draw", word: "draw", meaning: "画，绘画", phonetic: "/drɔː/", unit: 0, grade: 3, semester: 1 },
  { id: "look", word: "look", meaning: "看", phonetic: "/lʊk/", unit: 0, grade: 3, semester: 1 },
  { id: "guess", word: "guess", meaning: "猜；猜测", phonetic: "/ɡes/", unit: 0, grade: 3, semester: 1 },
  { id: "write", word: "write", meaning: "写", phonetic: "/raɪt/", unit: 0, grade: 3, semester: 1 },
  { id: "think", word: "think", meaning: "思考", phonetic: "/θɪŋk/", unit: 0, grade: 3, semester: 1 },
  { id: "read", word: "read", meaning: "阅读", phonetic: "/riːd/", unit: 0, grade: 3, semester: 1 },
  { id: "colour", word: "colour", meaning: "给...涂上颜色", phonetic: "/ˈkʌlə/", unit: 0, grade: 3, semester: 1 },
  { id: "play", word: "play", meaning: "玩", phonetic: "/pleɪ/", unit: 0, grade: 3, semester: 1 },
  { id: "hello", word: "hello", meaning: "你好", phonetic: "/həˈləʊ/", unit: 0, grade: 3, semester: 1 },

  // Unit 1 (22)
  { id: "what", word: "what", meaning: "什么", phonetic: "/wɒt/", unit: 1, grade: 3, semester: 1 },
  { id: "your", word: "your", meaning: "你的", phonetic: "/jɔː/", unit: 1, grade: 3, semester: 1 },
  { id: "name", word: "name", meaning: "名字", phonetic: "/neɪm/", unit: 1, grade: 3, semester: 1 },
  { id: "I", word: "I", meaning: "我", phonetic: "/aɪ/", unit: 1, grade: 3, semester: 1 },
  { id: "go", word: "go", meaning: "走，去", phonetic: "/ɡəʊ/", unit: 1, grade: 3, semester: 1 },
  { id: "everyone", word: "everyone", meaning: "每个人", phonetic: "/ˈevriwʌn/", unit: 1, grade: 3, semester: 1 },
  { id: "love", word: "love", meaning: "喜爱", phonetic: "/lʌv/", unit: 1, grade: 3, semester: 1 },
  { id: "a", word: "a(an)", meaning: "一个", phonetic: "/ə/", unit: 1, grade: 3, semester: 1 },
  { id: "parrot", word: "parrot", meaning: "鹦鹉", phonetic: "/ˈpærət/", unit: 1, grade: 3, semester: 1 },
  { id: "him", word: "him", meaning: "他", phonetic: "/hɪm/", unit: 1, grade: 3, semester: 1 },
  { id: "good", word: "good", meaning: "令人愉快的", phonetic: "/ɡʊd/", unit: 1, grade: 3, semester: 1 },
  { id: "morning", word: "morning", meaning: "早晨，早上", phonetic: "/ˈmɔːnɪŋ/", unit: 1, grade: 3, semester: 1 },
  { id: "goodbye", word: "goodbye(bye)", meaning: "再见", phonetic: "/ɡʊdˈbaɪ/", unit: 1, grade: 3, semester: 1 },
  { id: "night", word: "night", meaning: "夜晚", phonetic: "/naɪt/", unit: 1, grade: 3, semester: 1 },
  { id: "this", word: "this", meaning: "这，这个", phonetic: "/ðɪs/", unit: 1, grade: 3, semester: 1 },
  { id: "nice", word: "nice", meaning: "令人愉快的", phonetic: "/naɪs/", unit: 1, grade: 3, semester: 1 },
  { id: "meet", word: "meet", meaning: "认识，结识", phonetic: "/miːt/", unit: 1, grade: 3, semester: 1 },
  { id: "happy", word: "happy", meaning: "快乐的，高兴的", phonetic: "/ˈhæpi/", unit: 1, grade: 3, semester: 1 },
  { id: "birthday", word: "birthday", meaning: "生日", phonetic: "/ˈbɜːθdeɪ/", unit: 1, grade: 3, semester: 1 },
  { id: "afternoon", word: "afternoon", meaning: "下午", phonetic: "/ˌɑːftəˈnuːn/", unit: 1, grade: 3, semester: 1 },
  { id: "Ms", word: "Ms", meaning: "女士", phonetic: "/mɪz/", unit: 1, grade: 3, semester: 1 },
  { id: "how", word: "how", meaning: "如何，怎样", phonetic: "/haʊ/", unit: 1, grade: 3, semester: 1 },
  { id: "today", word: "today", meaning: "今天", phonetic: "/təˈdeɪ/", unit: 1, grade: 3, semester: 1 },
  { id: "too", word: "too", meaning: "也", phonetic: "/tuː/", unit: 1, grade: 3, semester: 1 },
  { id: "fine", word: "fine", meaning: "很好", phonetic: "/faɪn/", unit: 1, grade: 3, semester: 1 },
  { id: "children", word: "children", meaning: "儿童，小孩", phonetic: "/ˈtʃɪldrən/", unit: 1, grade: 3, semester: 1 },
  { id: "cut", word: "cut", meaning: "剪", phonetic: "/kʌt/", unit: 1, grade: 3, semester: 1 },
  { id: "my", word: "my", meaning: "我的", phonetic: "/maɪ/", unit: 1, grade: 3, semester: 1 },
  { id: "hi", word: "hi", meaning: "你好", phonetic: "/haɪ/", unit: 1, grade: 3, semester: 1 },

  // Unit 2 (32)
  { id: "colourful", word: "colourful", meaning: "色彩丰富的", phonetic: "/ˈkʌləfʊl/", unit: 2, grade: 3, semester: 1 },
  { id: "world", word: "world", meaning: "世界", phonetic: "/wɜːld/", unit: 2, grade: 3, semester: 1 },
  { id: "red", word: "red", meaning: "红色(的)", phonetic: "/red/", unit: 2, grade: 3, semester: 1 },
  { id: "pink", word: "pink", meaning: "粉红色(的)", phonetic: "/pɪŋk/", unit: 2, grade: 3, semester: 1 },
  { id: "yellow", word: "yellow", meaning: "黄色(的)", phonetic: "/ˈjeləʊ/", unit: 2, grade: 3, semester: 1 },
  { id: "orange", word: "orange", meaning: "橙色(的)", phonetic: "/ˈɒrɪndʒ/", unit: 2, grade: 3, semester: 1 },
  { id: "green", word: "green", meaning: "绿色(的)", phonetic: "/ɡriːn/", unit: 2, grade: 3, semester: 1 },
  { id: "brown", word: "brown", meaning: "棕色(的)", phonetic: "/braʊn/", unit: 2, grade: 3, semester: 1 },
  { id: "black", word: "black", meaning: "黑色(的)", phonetic: "/blæk/", unit: 2, grade: 3, semester: 1 },
  { id: "blue", word: "blue", meaning: "蓝色(的)", phonetic: "/bluː/", unit: 2, grade: 3, semester: 1 },
  { id: "white", word: "white", meaning: "白色(的)", phonetic: "/waɪt/", unit: 2, grade: 3, semester: 1 },
  { id: "purple", word: "purple", meaning: "紫色(的)", phonetic: "/ˈpɜːpəl/", unit: 2, grade: 3, semester: 1 },
  { id: "the", word: "the", meaning: "这/那个", phonetic: "/ðə/", unit: 2, grade: 3, semester: 1 },
  { id: "rainbow", word: "rainbow", meaning: "彩虹", phonetic: "/ˈreɪnbəʊ/", unit: 2, grade: 3, semester: 1 },
  { id: "it", word: "it", meaning: "它", phonetic: "/ɪt/", unit: 2, grade: 3, semester: 1 },
  { id: "oh", word: "oh", meaning: "噢，哦", phonetic: "/əʊ/", unit: 2, grade: 3, semester: 1 },
  { id: "start", word: "start", meaning: "开始", phonetic: "/stɑːt/", unit: 2, grade: 3, semester: 1 },
  { id: "necklace", word: "necklace", meaning: "项链", phonetic: "/ˈnekləs/", unit: 2, grade: 3, semester: 1 },
  { id: "for", word: "for", meaning: "给", phonetic: "/fɔː/", unit: 2, grade: 3, semester: 1 },
  { id: "mum", word: "mum", meaning: "妈妈", phonetic: "/mʌm/", unit: 2, grade: 3, semester: 1 },
  { id: "old", word: "old", meaning: "旧的", phonetic: "/əʊld/", unit: 2, grade: 3, semester: 1 },
  { id: "can", word: "can", meaning: "能，可以", phonetic: "/kæn/", unit: 2, grade: 3, semester: 1 },
  { id: "paint", word: "paint", meaning: "给......涂颜料", phonetic: "/peɪnt/", unit: 2, grade: 3, semester: 1 },
  { id: "only", word: "only", meaning: "只有，仅", phonetic: "/ˈəʊnli/", unit: 2, grade: 3, semester: 1 },
  { id: "me", word: "me", meaning: "我", phonetic: "/miː/", unit: 2, grade: 3, semester: 1 },
  { id: "thank", word: "thank", meaning: "感谢", phonetic: "/θæŋk/", unit: 2, grade: 3, semester: 1 },
  { id: "dear", word: "dear", meaning: "亲爱的", phonetic: "/dɪə/", unit: 2, grade: 3, semester: 1 },
  { id: "at", word: "at", meaning: "朝，向", phonetic: "/æt/", unit: 2, grade: 3, semester: 1 },
  { id: "butterfly", word: "butterfly", meaning: "蝴蝶", phonetic: "/ˈbʌtəflaɪ/", unit: 2, grade: 3, semester: 1 },
  { id: "lovely", word: "lovely", meaning: "美丽的；可爱的", phonetic: "/ˈlʌvli/", unit: 2, grade: 3, semester: 1 },
  { id: "little", word: "little", meaning: "小的", phonetic: "/ˈlɪtəl/", unit: 2, grade: 3, semester: 1 },
  { id: "favourite", word: "favourite", meaning: "最喜欢的", phonetic: "/ˈfeɪvərɪt/", unit: 2, grade: 3, semester: 1 },
  { id: "no", word: "no", meaning: "不，不是", phonetic: "/nəʊ/", unit: 2, grade: 3, semester: 1 },
  { id: "that", word: "that", meaning: "那，那个", phonetic: "/ðæt/", unit: 2, grade: 3, semester: 1 },
  { id: "right", word: "right", meaning: "正确的，对的", phonetic: "/raɪt/", unit: 2, grade: 3, semester: 1 },

  // Unit 3 (30)
  { id: "number", word: "number", meaning: "数字", phonetic: "/ˈnʌmbə/", unit: 3, grade: 3, semester: 1 },
  { id: "funny", word: "funny", meaning: "有趣的", phonetic: "/ˈfʌni/", unit: 3, grade: 3, semester: 1 },
  { id: "tiger", word: "tiger", meaning: "老虎", phonetic: "/ˈtaɪɡə/", unit: 3, grade: 3, semester: 1 },
  { id: "jump", word: "jump", meaning: "跳，跃", phonetic: "/dʒʌmp/", unit: 3, grade: 3, semester: 1 },
  { id: "do", word: "do", meaning: "做", phonetic: "/duː/", unit: 3, grade: 3, semester: 1 },
  { id: "ten", word: "ten", meaning: "十", phonetic: "/ten/", unit: 3, grade: 3, semester: 1 },
  { id: "nine", word: "nine", meaning: "九", phonetic: "/naɪn/", unit: 3, grade: 3, semester: 1 },
  { id: "eight", word: "eight", meaning: "八", phonetic: "/eɪt/", unit: 3, grade: 3, semester: 1 },
  { id: "seven", word: "seven", meaning: "七", phonetic: "/ˈsevən/", unit: 3, grade: 3, semester: 1 },
  { id: "six", word: "six", meaning: "六", phonetic: "/sɪks/", unit: 3, grade: 3, semester: 1 },
  { id: "five", word: "five", meaning: "五", phonetic: "/faɪv/", unit: 3, grade: 3, semester: 1 },
  { id: "four", word: "four", meaning: "四", phonetic: "/fɔː/", unit: 3, grade: 3, semester: 1 },
  { id: "three", word: "three", meaning: "三", phonetic: "/θriː/", unit: 3, grade: 3, semester: 1 },
  { id: "two", word: "two", meaning: "二", phonetic: "/tuː/", unit: 3, grade: 3, semester: 1 },
  { id: "one", word: "one", meaning: "一", phonetic: "/wʌn/", unit: 3, grade: 3, semester: 1 },
  { id: "zero", word: "zero", meaning: "零", phonetic: "/ˈzɪərəʊ/", unit: 3, grade: 3, semester: 1 },
  { id: "duck", word: "duck", meaning: "鸭子", phonetic: "/dʌk/", unit: 3, grade: 3, semester: 1 },
  { id: "show", word: "show", meaning: "节目", phonetic: "/ʃəʊ/", unit: 3, grade: 3, semester: 1 },
  { id: "about", word: "about", meaning: "大约", phonetic: "/əˈbaʊt/", unit: 3, grade: 3, semester: 1 },
  { id: "dad", word: "dad", meaning: "爸爸", phonetic: "/dæd/", unit: 3, grade: 3, semester: 1 },
  { id: "please", word: "please", meaning: "请", phonetic: "/pliːz/", unit: 3, grade: 3, semester: 1 },
  { id: "hurry", word: "hurry", meaning: "赶紧，匆忙", phonetic: "/ˈhʌri/", unit: 3, grade: 3, semester: 1 },
  { id: "up", word: "up", meaning: "向上，往上", phonetic: "/ʌp/", unit: 3, grade: 3, semester: 1 },
  { id: "wrong", word: "wrong", meaning: "有问题的", phonetic: "/rɒŋ/", unit: 3, grade: 3, semester: 1 },
  { id: "see", word: "see", meaning: "看见，看到", phonetic: "/siː/", unit: 3, grade: 3, semester: 1 },
  { id: "many", word: "many", meaning: "许多", phonetic: "/ˈmeni/", unit: 3, grade: 3, semester: 1 },
  { id: "how_many", word: "how many", meaning: "多少", phonetic: "/haʊ ˈmeni/", unit: 3, grade: 3, semester: 1 },
  { id: "get", word: "get", meaning: "移动，去", phonetic: "/ɡet/", unit: 3, grade: 3, semester: 1 },
  { id: "out", word: "out", meaning: "向外", phonetic: "/aʊt/", unit: 3, grade: 3, semester: 1 },
  { id: "have", word: "have", meaning: "进行", phonetic: "/hæv/", unit: 3, grade: 3, semester: 1 },
  { id: "help", word: "help", meaning: "帮助", phonetic: "/help/", unit: 3, grade: 3, semester: 1 },
  { id: "great", word: "great", meaning: "极好的", phonetic: "/ɡreɪt/", unit: 3, grade: 3, semester: 1 },
  { id: "we", word: "we", meaning: "我们", phonetic: "/wiː/", unit: 3, grade: 3, semester: 1 },
  { id: "late", word: "late", meaning: "迟到的", phonetic: "/leɪt/", unit: 3, grade: 3, semester: 1 },
  { id: "safe", word: "safe", meaning: "安全的", phonetic: "/seɪf/", unit: 3, grade: 3, semester: 1 },
  { id: "people", word: "people", meaning: "人", phonetic: "/ˈpiːpəl/", unit: 3, grade: 3, semester: 1 },
  { id: "call", word: "call", meaning: "(给.....)打电话", phonetic: "/kɔːl/", unit: 3, grade: 3, semester: 1 },

  // Unit 4 (20)
  { id: "school", word: "school", meaning: "学校", phonetic: "/skuːl/", unit: 4, grade: 3, semester: 1 },
  { id: "thing", word: "thing", meaning: "东西，物", phonetic: "/θɪŋ/", unit: 4, grade: 3, semester: 1 },
  { id: "pencil", word: "pencil", meaning: "铅笔", phonetic: "/ˈpensəl/", unit: 4, grade: 3, semester: 1 },
  { id: "case", word: "case", meaning: "盒子", phonetic: "/keɪs/", unit: 4, grade: 3, semester: 1 },
  { id: "pencilcase", word: "pencil case", meaning: "笔袋；铅笔盒", phonetic: "/ˈpensəl keɪs/", unit: 4, grade: 3, semester: 1 },
  { id: "pen", word: "pen", meaning: "钢笔", phonetic: "/pen/", unit: 4, grade: 3, semester: 1 },
  { id: "eraser", word: "eraser", meaning: "橡皮", phonetic: "/ɪˈreɪzə/", unit: 4, grade: 3, semester: 1 },
  { id: "schoolbag", word: "schoolbag", meaning: "书包", phonetic: "/ˈskuːlbæɡ/", unit: 4, grade: 3, semester: 1 },
  { id: "ruler", word: "ruler", meaning: "尺子，直尺", phonetic: "/ˈruːlə/", unit: 4, grade: 3, semester: 1 },
  { id: "book", word: "book", meaning: "书籍", phonetic: "/bʊk/", unit: 4, grade: 3, semester: 1 },
  { id: "home", word: "home", meaning: "到家，回家", phonetic: "/həʊm/", unit: 4, grade: 3, semester: 1 },
  { id: "where", word: "where", meaning: "在哪里", phonetic: "/weə/", unit: 4, grade: 3, semester: 1 },
  { id: "picture", word: "picture", meaning: "图画", phonetic: "/ˈpɪktʃə/", unit: 4, grade: 3, semester: 1 },
  { id: "on", word: "on", meaning: "在.....上面", phonetic: "/ɒn/", unit: 4, grade: 3, semester: 1 },
  { id: "wall", word: "wall", meaning: "墙", phonetic: "/wɔːl/", unit: 4, grade: 3, semester: 1 },
  { id: "paper", word: "paper", meaning: "纸", phonetic: "/ˈpeɪpə/", unit: 4, grade: 3, semester: 1 },
  { id: "open", word: "open", meaning: "打开", phonetic: "/ˈəʊpən/", unit: 4, grade: 3, semester: 1 },
  { id: "take", word: "take", meaning: "拿", phonetic: "/teɪk/", unit: 4, grade: 3, semester: 1 },
  { id: "rope", word: "rope", meaning: "绳索", phonetic: "/rəʊp/", unit: 4, grade: 3, semester: 1 },
  { id: "skipping_rope", word: "skipping rope", meaning: "跳绳", phonetic: "/ˈskɪpɪŋ rəʊp/", unit: 4, grade: 3, semester: 1 },
  { id: "hooray", word: "hooray", meaning: "好哇", phonetic: "/hʊˈreɪ/", unit: 4, grade: 3, semester: 1 },

  // Unit 5 (28)
  { id: "classroom", word: "classroom", meaning: "教室", phonetic: "/ˈklɑːsruːm/", unit: 5, grade: 3, semester: 1 },
  { id: "board", word: "board", meaning: "板子", phonetic: "/bɔːd/", unit: 5, grade: 3, semester: 1 },
  { id: "door", word: "door", meaning: "门", phonetic: "/dɔː/", unit: 5, grade: 3, semester: 1 },
  { id: "window", word: "window", meaning: "窗户", phonetic: "/ˈwɪndəʊ/", unit: 5, grade: 3, semester: 1 },
  { id: "desk", word: "desk", meaning: "书桌", phonetic: "/desk/", unit: 5, grade: 3, semester: 1 },
  { id: "chair", word: "chair", meaning: "椅子", phonetic: "/tʃeə/", unit: 5, grade: 3, semester: 1 },
  { id: "floor", word: "floor", meaning: "地面", phonetic: "/flɔː/", unit: 5, grade: 3, semester: 1 },
  { id: "ball", word: "ball", meaning: "球", phonetic: "/bɔːl/", unit: 5, grade: 3, semester: 1 },
  { id: "behind", word: "behind", meaning: "在.....后面", phonetic: "/bɪˈhaɪnd/", unit: 5, grade: 3, semester: 1 },
  { id: "front", word: "front", meaning: "前面", phonetic: "/frʌnt/", unit: 5, grade: 3, semester: 1 },
  { id: "in_front_of", word: "in front of", meaning: "在......前面", phonetic: "/ɪn frʌnt ɒv/", unit: 5, grade: 3, semester: 1 },
  { id: "beside", word: "beside", meaning: "在....旁边", phonetic: "/bɪˈsaɪd/", unit: 5, grade: 3, semester: 1 },
  { id: "under", word: "under", meaning: "在......下面", phonetic: "/ˈʌndə/", unit: 5, grade: 3, semester: 1 },
  { id: "bird", word: "bird", meaning: "鸟", phonetic: "/bɜːd/", unit: 5, grade: 3, semester: 1 },
  { id: "now", word: "now", meaning: "现在", phonetic: "/naʊ/", unit: 5, grade: 3, semester: 1 },
  { id: "class", word: "class", meaning: "班，班级", phonetic: "/klɑːs/", unit: 5, grade: 3, semester: 1 },
  { id: "wow", word: "wow", meaning: "哇，呀", phonetic: "/waʊ/", unit: 5, grade: 3, semester: 1 },
  { id: "happen", word: "happen", meaning: "发生", phonetic: "/ˈhæpən/", unit: 5, grade: 3, semester: 1 },
  { id: "next", word: "next", meaning: "紧接下来；随后", phonetic: "/nekst/", unit: 5, grade: 3, semester: 1 },
  { id: "outside", word: "outside", meaning: "外面，外部", phonetic: "/ˌaʊtˈsaɪd/", unit: 5, grade: 3, semester: 1 },
  { id: "keep", word: "keep", meaning: "饲养", phonetic: "/kiːp/", unit: 5, grade: 3, semester: 1 },
  { id: "with", word: "with", meaning: "和·...一起", phonetic: "/wɪð/", unit: 5, grade: 3, semester: 1 },
  { id: "over", word: "over", meaning: "结束", phonetic: "/ˈəʊvə/", unit: 5, grade: 3, semester: 1 },
  { id: "clean", word: "clean", meaning: "(使)清扫 青理", phonetic: "/kliːn/", unit: 5, grade: 3, semester: 1 },
  { id: "blackboard", word: "blackboard", meaning: "黑板", phonetic: "/ˈblækbɔːd/", unit: 5, grade: 3, semester: 1 },
  { id: "sweep", word: "sweep", meaning: "打扫", phonetic: "/swiːp/", unit: 5, grade: 3, semester: 1 },
  { id: "put", word: "put", meaning: "放，放置", phonetic: "/pʊt/", unit: 5, grade: 3, semester: 1 },
  { id: "tomorrow", word: "tomorrow", meaning: "明天", phonetic: "/təˈmɒrəʊ/", unit: 5, grade: 3, semester: 1 },
  { id: "national_flag", word: "national flag", meaning: "国旗", phonetic: "/ˈnæʃnəl flæɡ/", unit: 5, grade: 3, semester: 1 },
  { id: "they", word: "they", meaning: "他们；她们；它们", phonetic: "/ðeɪ/", unit: 5, grade: 3, semester: 1 },

  // Unit 6 (20)
  { id: "family", word: "family", meaning: "家，家庭", phonetic: "/ˈfæməli/", unit: 6, grade: 3, semester: 1 },
  { id: "brother", word: "brother", meaning: "哥哥；弟弟", phonetic: "/ˈbrʌðə/", unit: 6, grade: 3, semester: 1 },
  { id: "sister", word: "sister", meaning: "姐姐；妹妹", phonetic: "/ˈsɪstə/", unit: 6, grade: 3, semester: 1 },
  { id: "grandpa", word: "grandpa", meaning: "爷爷；外公", phonetic: "/ˈɡrænpɑː/", unit: 6, grade: 3, semester: 1 },
  { id: "grandma", word: "grandma", meaning: "奶奶；外婆", phonetic: "/ˈɡrænmɑː/", unit: 6, grade: 3, semester: 1 },
  { id: "some", word: "some", meaning: "一些", phonetic: "/sʌm/", unit: 6, grade: 3, semester: 1 },
  { id: "tea", word: "tea", meaning: "茶", phonetic: "/tiː/", unit: 6, grade: 3, semester: 1 },
  { id: "uncle", word: "uncle", meaning: "叔叔；伯伯；舅舅；姑父；姨父", phonetic: "/ˈʌŋkəl/", unit: 6, grade: 3, semester: 1 },
  { id: "aunt", word: "aunt", meaning: "阿姨；姑妈；伯母；舅妈；姨妈", phonetic: "/ɑːnt/", unit: 6, grade: 3, semester: 1 },
  { id: "long", word: "long", meaning: "长时间的", phonetic: "/lɒŋ/", unit: 6, grade: 3, semester: 1 },
  { id: "time", word: "time", meaning: "时间", phonetic: "/taɪm/", unit: 6, grade: 3, semester: 1 },
  { id: "sport", word: "sport", meaning: "体育运动", phonetic: "/spɔːt/", unit: 6, grade: 3, semester: 1 },
  { id: "day", word: "day", meaning: "天", phonetic: "/deɪ/", unit: 6, grade: 3, semester: 1 },
  { id: "their", word: "their", meaning: "他们的", phonetic: "/ðeə/", unit: 6, grade: 3, semester: 1 },
  { id: "win", word: "win", meaning: "获胜，赢", phonetic: "/wɪn/", unit: 6, grade: 3, semester: 1 },
  { id: "job", word: "job", meaning: "工作，任务", phonetic: "/dʒɒb/", unit: 6, grade: 3, semester: 1 },
  { id: "best", word: "best", meaning: "最好的", phonetic: "/best/", unit: 6, grade: 3, semester: 1 },
  { id: "all", word: "all", meaning: "完全", phonetic: "/ɔːl/", unit: 6, grade: 3, semester: 1 },

  // ==================== 三年级下册（semester: 2）====================

  // Unit 1 (27)
  { id: "feeling", word: "feeling", meaning: "感觉", phonetic: "/ˈfiːlɪŋ/", unit: 1, grade: 3, semester: 2 },
  { id: "tired", word: "tired", meaning: "疲惫的", phonetic: "/ˈtaɪəd/", unit: 1, grade: 3, semester: 2 },
  { id: "sad", word: "sad", meaning: "难过的", phonetic: "/sæd/", unit: 1, grade: 3, semester: 2 },
  { id: "angry", word: "angry", meaning: "生气的", phonetic: "/ˈæŋɡri/", unit: 1, grade: 3, semester: 2 },
  { id: "scared", word: "scared", meaning: "害怕的", phonetic: "/skeəd/", unit: 1, grade: 3, semester: 2 },
  { id: "cry", word: "cry", meaning: "哭", phonetic: "/kraɪ/", unit: 1, grade: 3, semester: 2 },
  { id: "laugh", word: "laugh", meaning: "笑", phonetic: "/lɑːf/", unit: 1, grade: 3, semester: 2 },
  { id: "stamp", word: "stamp", meaning: "跺(脚)", phonetic: "/stæmp/", unit: 1, grade: 3, semester: 2 },
  { id: "sleep", word: "sleep", meaning: "睡觉", phonetic: "/sliːp/", unit: 1, grade: 3, semester: 2 },
  { id: "new", word: "new", meaning: "新的", phonetic: "/njuː/", unit: 1, grade: 3, semester: 2 },
  { id: "game", word: "game", meaning: "游戏", phonetic: "/ɡeɪm/", unit: 1, grade: 3, semester: 2 },
  { id: "excited", word: "excited", meaning: "兴奋的", phonetic: "/ɪkˈsaɪtɪd/", unit: 1, grade: 3, semester: 2 },
  { id: "sorry", word: "sorry", meaning: "对不起", phonetic: "/ˈsɒri/", unit: 1, grade: 3, semester: 2 },
  { id: "like", word: "like", meaning: "喜欢", phonetic: "/laɪk/", unit: 1, grade: 3, semester: 2 },
  { id: "but", word: "but", meaning: "但是", phonetic: "/bʌt/", unit: 1, grade: 3, semester: 2 },
  { id: "unhappy", word: "unhappy", meaning: "不开心的", phonetic: "/ʌnˈhæpi/", unit: 1, grade: 3, semester: 2 },
  { id: "worried", word: "worried", meaning: "担心的", phonetic: "/ˈwʌrid/", unit: 1, grade: 3, semester: 2 },
  { id: "not", word: "not", meaning: "不;不是", phonetic: "/nɒt/", unit: 1, grade: 3, semester: 2 },
  { id: "feel", word: "feel", meaning: "感觉到", phonetic: "/fiːl/", unit: 1, grade: 3, semester: 2 },
  { id: "find", word: "find", meaning: "找到", phonetic: "/faɪnd/", unit: 1, grade: 3, semester: 2 },
  { id: "doll", word: "doll", meaning: "玩偶", phonetic: "/dɒl/", unit: 1, grade: 3, semester: 2 },
  { id: "football", word: "football", meaning: "足球", phonetic: "/ˈfʊtbɔːl/", unit: 1, grade: 3, semester: 2 },
  { id: "eat", word: "eat", meaning: "吃", phonetic: "/iːt/", unit: 1, grade: 3, semester: 2 },
  { id: "his", word: "his", meaning: "他的", phonetic: "/hɪz/", unit: 1, grade: 3, semester: 2 },
  { id: "cake", word: "cake", meaning: "蛋糕", phonetic: "/keɪk/", unit: 1, grade: 3, semester: 2 },
  { id: "big", word: "big", meaning: "大的", phonetic: "/bɪɡ/", unit: 1, grade: 3, semester: 2 },
  { id: "mouse", word: "mouse", meaning: "老鼠", phonetic: "/maʊs/", unit: 1, grade: 3, semester: 2 },

  // Unit 2 (30)
  { id: "know", word: "know", meaning: "了解", phonetic: "/nəʊ/", unit: 2 },
  { id: "body", word: "body", meaning: "身体", phonetic: "/ˈbɒdi/", unit: 2 },
  { id: "rock", word: "rock", meaning: "摇滚乐", phonetic: "/rɒk/", unit: 2 },
  { id: "song", word: "song", meaning: "歌曲", phonetic: "/sɒŋ/", unit: 2 },
  { id: "touch", word: "touch", meaning: "触摸", phonetic: "/tʌtʃ/", unit: 2 },
  { id: "head", word: "head", meaning: "头", phonetic: "/hed/", unit: 2 },
  { id: "eye", word: "eye", meaning: "眼睛", phonetic: "/aɪ/", unit: 2 },
  { id: "hair", word: "hair", meaning: "头发", phonetic: "/heə/", unit: 2 },
  { id: "short", word: "short", meaning: "短的", phonetic: "/ʃɔːt/", unit: 2 },
  { id: "small", word: "small", meaning: "小的", phonetic: "/smɔːl/", unit: 2 },
  { id: "ear", word: "ear", meaning: "耳朵", phonetic: "/ɪə/", unit: 2 },
  { id: "wave", word: "wave", meaning: "摆动", phonetic: "/weɪv/", unit: 2 },
  { id: "leg", word: "leg", meaning: "腿", phonetic: "/leɡ/", unit: 2 },
  { id: "foot", word: "foot", meaning: "脚", phonetic: "/fʊt/", unit: 2 },
  { id: "nose", word: "nose", meaning: "鼻子", phonetic: "/nəʊz/", unit: 2 },
  { id: "face", word: "face", meaning: "脸", phonetic: "/feɪs/", unit: 2 },
  { id: "arm", word: "arm", meaning: "手臂", phonetic: "/ɑːm/", unit: 2 },
  { id: "hand", word: "hand", meaning: "手", phonetic: "/hænd/", unit: 2 },
  { id: "mouth", word: "mouth", meaning: "嘴", phonetic: "/maʊθ/", unit: 2 },
  { id: "tooth", word: "tooth", meaning: "牙", phonetic: "/tuːθ/", unit: 2 },
  { id: "prize", word: "prize", meaning: "奖品", phonetic: "/praɪz/", unit: 2 },
  { id: "bike", word: "bike", meaning: "自行车", phonetic: "/baɪk/", unit: 2 },
  { id: "race", word: "race", meaning: "竞赛", phonetic: "/reɪs/", unit: 2 },
  { id: "stretch", word: "stretch", meaning: "伸展", phonetic: "/stretʃ/", unit: 2 },
  { id: "shake", word: "shake", meaning: "摇动", phonetic: "/ʃeɪk/", unit: 2 },
  { id: "here", word: "here", meaning: "在这里", phonetic: "/hɪə/", unit: 2 },
  { id: "Mr", word: "Mr", meaning: "先生", phonetic: "/ˈmɪstə/", unit: 2 },
  { id: "back", word: "back", meaning: "回到原处", phonetic: "/bæk/", unit: 2 },
  { id: "worry", word: "worry", meaning: "担心", phonetic: "/ˈwʌri/", unit: 2 },
  { id: "robot", word: "robot", meaning: "机器人", phonetic: "/ˈrəʊbɒt/", unit: 2 },

  // Unit 3 (41)
  { id: "so", word: "so", meaning: "这么", phonetic: "/səʊ/", unit: 3 },
  { id: "cool", word: "cool", meaning: "酷的", phonetic: "/kuːl/", unit: 3 },
  { id: "clothes", word: "clothes", meaning: "衣服", phonetic: "/kləʊðz/", unit: 3 },
  { id: "wear", word: "wear", meaning: "穿", phonetic: "/weə/", unit: 3 },
  { id: "cap", word: "cap", meaning: "帽子", phonetic: "/kæp/", unit: 3 },
  { id: "T-shirt", word: "T-shirt", meaning: "T恤", phonetic: "/ˈtiːʃɜːt/", unit: 3 },
  { id: "trousers", word: "trousers", meaning: "裤子", phonetic: "/ˈtraʊzəz/", unit: 3 },
  { id: "sock", word: "sock", meaning: "袜子", phonetic: "/sɒk/", unit: 3 },
  { id: "shiny", word: "shiny", meaning: "有光泽的", phonetic: "/ˈʃaɪni/", unit: 3 },
  { id: "shoe", word: "shoe", meaning: "鞋", phonetic: "/ʃuː/", unit: 3 },
  { id: "dress", word: "dress", meaning: "连衣裙", phonetic: "/dres/", unit: 3 },
  { id: "sweater", word: "sweater", meaning: "毛线衣", phonetic: "/ˈswetə/", unit: 3 },
  { id: "skirt", word: "skirt", meaning: "半身裙", phonetic: "/skɜːt/", unit: 3 },
  { id: "shirt", word: "shirt", meaning: "衬衫", phonetic: "/ʃɜːt/", unit: 3 },
  { id: "coat", word: "coat", meaning: "外套", phonetic: "/kəʊt/", unit: 3 },
  { id: "shorts", word: "shorts", meaning: "短裤", phonetic: "/ʃɔːts/", unit: 3 },
  { id: "king", word: "king", meaning: "国王", phonetic: "/kɪŋ/", unit: 3 },
  { id: "want", word: "want", meaning: "想要", phonetic: "/wɒnt/", unit: 3 },
  { id: "beautiful", word: "beautiful", meaning: "美丽的", phonetic: "/ˈbjuːtɪfʊl/", unit: 3 },
  { id: "make", word: "make", meaning: "做", phonetic: "/meɪk/", unit: 3 },
  { id: "magic", word: "magic", meaning: "神奇的", phonetic: "/ˈmædʒɪk/", unit: 3 },
  { id: "people", word: "people", meaning: "人", phonetic: "/ˈpiːpəl/", unit: 3 },
  { id: "them", word: "them", meaning: "它们", phonetic: "/ðem/", unit: 3 },
  { id: "after", word: "after", meaning: "在……后", phonetic: "/ˈɑːftə/", unit: 3 },
  { id: "month", word: "month", meaning: "月", phonetic: "/mʌnθ/", unit: 3 },
  { id: "try", word: "try", meaning: "试", phonetic: "/traɪ/", unit: 3 },
  { id: "why", word: "why", meaning: "为什么", phonetic: "/waɪ/", unit: 3 },
  { id: "wonderful", word: "wonderful", meaning: "令人惊叹的", phonetic: "/ˈwʌndəfʊl/", unit: 3 },
  { id: "most", word: "most", meaning: "最", phonetic: "/məʊst/", unit: 3 },
  { id: "any", word: "any", meaning: "其他的", phonetic: "/ˈeni/", unit: 3 },
  { id: "or", word: "or", meaning: "或", phonetic: "/ɔː/", unit: 3 },
  { id: "fox", word: "fox", meaning: "狐狸", phonetic: "/fɒks/", unit: 3 },
  { id: "monkey", word: "monkey", meaning: "猴子", phonetic: "/ˈmʌŋki/", unit: 3 },
  { id: "tell", word: "tell", meaning: "告诉", phonetic: "/tel/", unit: 3 },
  { id: "truth", word: "truth", meaning: "真相", phonetic: "/truːθ/", unit: 3 },
  { id: "wash", word: "wash", meaning: "洗", phonetic: "/wɒʃ/", unit: 3 },
  { id: "hang", word: "hang", meaning: "悬挂", phonetic: "/hæŋ/", unit: 3 },
  { id: "hat", word: "hat", meaning: "帽子", phonetic: "/hæt/", unit: 3 },
  { id: "jeans", word: "jeans", meaning: "牛仔裤", phonetic: "/dʒiːnz/", unit: 3 },
  { id: "boot", word: "boot", meaning: "靴子", phonetic: "/buːt/", unit: 3 },
  { id: "robe", word: "robe", meaning: "长袍", phonetic: "/rəʊb/", unit: 3 },

  // Unit 4 (42)
  { id: "rain", word: "rain", meaning: "雨", phonetic: "/reɪn/", unit: 4 },
  { id: "sun", word: "sun", meaning: "阳光", phonetic: "/sʌn/", unit: 4 },
  { id: "rainy", word: "rainy", meaning: "多雨的", phonetic: "/ˈreɪni/", unit: 4 },
  { id: "run", word: "run", meaning: "跑", phonetic: "/rʌn/", unit: 4 },
  { id: "windy", word: "windy", meaning: "多风的", phonetic: "/ˈwɪndi/", unit: 4 },
  { id: "fly", word: "fly", meaning: "放飞", phonetic: "/flaɪ/", unit: 4 },
  { id: "kite", word: "kite", meaning: "风筝", phonetic: "/kaɪt/", unit: 4 },
  { id: "park", word: "park", meaning: "公园", phonetic: "/pɑːk/", unit: 4 },
  { id: "hot", word: "hot", meaning: "炎热的", phonetic: "/hɒt/", unit: 4 },
  { id: "sunny", word: "sunny", meaning: "阳光充足的", phonetic: "/ˈsʌni/", unit: 4 },
  { id: "swim", word: "swim", meaning: "游泳", phonetic: "/swɪm/", unit: 4 },
  { id: "water", word: "water", meaning: "水", phonetic: "/ˈwɔːtə/", unit: 4 },
  { id: "cold", word: "cold", meaning: "寒冷的", phonetic: "/kəʊld/", unit: 4 },
  { id: "snowy", word: "snowy", meaning: "多雪的", phonetic: "/ˈsnəʊi/", unit: 4 },
  { id: "throw", word: "throw", meaning: "投;扔", phonetic: "/θrəʊ/", unit: 4 },
  { id: "snowball", word: "snowball", meaning: "雪球", phonetic: "/ˈsnəʊbɔːl/", unit: 4 },
  { id: "umbrella", word: "umbrella", meaning: "雨伞", phonetic: "/ʌmˈbrelə/", unit: 4 },
  { id: "warm", word: "warm", meaning: "保暖的", phonetic: "/wɔːm/", unit: 4 },
  { id: "music", word: "music", meaning: "音乐", phonetic: "/ˈmjuːzɪk/", unit: 4 },
  { id: "weather", word: "weather", meaning: "天气", phonetic: "/ˈweðə/", unit: 4 },
  { id: "bookshop", word: "bookshop", meaning: "书店", phonetic: "/ˈbʊkʃɒp/", unit: 4 },
  { id: "wait", word: "wait", meaning: "等", phonetic: "/weɪt/", unit: 4 },
  { id: "wet", word: "wet", meaning: "湿的", phonetic: "/wet/", unit: 4 },
  { id: "again", word: "again", meaning: "又", phonetic: "/əˈɡen/", unit: 4 },
  { id: "dry", word: "dry", meaning: "干燥的", phonetic: "/draɪ/", unit: 4 },
  { id: "sell", word: "sell", meaning: "卖", phonetic: "/sel/", unit: 4 },
  { id: "these", word: "these", meaning: "这些", phonetic: "/ðiːz/", unit: 4 },
  { id: "idea", word: "idea", meaning: "主意", phonetic: "/aɪˈdɪə/", unit: 4 },
  { id: "club", word: "club", meaning: "俱乐部", phonetic: "/klʌb/", unit: 4 },
  { id: "welcome", word: "welcome", meaning: "欢迎", phonetic: "/ˈwelkəm/", unit: 4 },
  { id: "stand", word: "stand", meaning: "站立", phonetic: "/stænd/", unit: 4 },
  { id: "board", word: "board", meaning: "公告牌", phonetic: "/bɔːd/", unit: 4 },
  { id: "walk", word: "walk", meaning: "走", phonetic: "/wɔːk/", unit: 4 },
  { id: "carefully", word: "carefully", meaning: "小心地", phonetic: "/ˈkeəfəli/", unit: 4 },
  { id: "tree", word: "tree", meaning: "树", phonetic: "/triː/", unit: 4 },
  { id: "spring", word: "spring", meaning: "春天", phonetic: "/sprɪŋ/", unit: 4 },
  { id: "summer", word: "summer", meaning: "夏天", phonetic: "/ˈsʌmə/", unit: 4 },
  { id: "autumn", word: "autumn", meaning: "秋天", phonetic: "/ˈɔːtəm/", unit: 4 },
  { id: "winter", word: "winter", meaning: "冬天", phonetic: "/ˈwɪntə/", unit: 4 },
  { id: "season", word: "season", meaning: "季节", phonetic: "/ˈsiːzən/", unit: 4 },
  { id: "drawing", word: "drawing", meaning: "图画", phonetic: "/ˈdrɔːɪŋ/", unit: 4 },
  { id: "cloudy", word: "cloudy", meaning: "多云的", phonetic: "/ˈklaʊdi/", unit: 4 },

  // Unit 5 (24)
  { id: "week", word: "week", meaning: "星期", phonetic: "/wiːk/", unit: 5 },
  { id: "Monday", word: "Monday", meaning: "星期一", phonetic: "/ˈmʌndeɪ/", unit: 5 },
  { id: "Tuesday", word: "Tuesday", meaning: "星期二", phonetic: "/ˈtjuːzdeɪ/", unit: 5 },
  { id: "Wednesday", word: "Wednesday", meaning: "星期三", phonetic: "/ˈwenzdeɪ/", unit: 5 },
  { id: "Thursday", word: "Thursday", meaning: "星期四", phonetic: "/ˈθɜːzdeɪ/", unit: 5 },
  { id: "Friday", word: "Friday", meaning: "星期五", phonetic: "/ˈfraɪdeɪ/", unit: 5 },
  { id: "Saturday", word: "Saturday", meaning: "星期六", phonetic: "/ˈsætədeɪ/", unit: 5 },
  { id: "Sunday", word: "Sunday", meaning: "星期日", phonetic: "/ˈsʌndeɪ/", unit: 5 },
  { id: "before", word: "before", meaning: "在……以前", phonetic: "/bɪˈfɔː/", unit: 5 },
  { id: "room", word: "room", meaning: "房间", phonetic: "/ruːm/", unit: 5 },
  { id: "close", word: "close", meaning: "关;闭合", phonetic: "/kləʊz/", unit: 5 },
  { id: "much", word: "much", meaning: "非常", phonetic: "/mʌtʃ/", unit: 5 },
  { id: "rabbit", word: "rabbit", meaning: "兔", phonetic: "/ˈræbɪt/", unit: 5 },
  { id: "cat", word: "cat", meaning: "猫", phonetic: "/kæt/", unit: 5 },
  { id: "fish", word: "fish", meaning: "鱼", phonetic: "/fɪʃ/", unit: 5 },
  { id: "busy", word: "busy", meaning: "忙碌的", phonetic: "/ˈbɪzi/", unit: 5 },
  { id: "every", word: "every", meaning: "每一个", phonetic: "/ˈevri/", unit: 5 },
  { id: "cooking", word: "cooking", meaning: "做饭", phonetic: "/ˈkʊkɪŋ/", unit: 5 },
  { id: "cook", word: "cook", meaning: "烹调", phonetic: "/kʊk/", unit: 5 },
  { id: "Chinese", word: "Chinese", meaning: "中国的", phonetic: "/ˌtʃaɪˈniːz/", unit: 5 },
  { id: "chess", word: "chess", meaning: "国际象棋", phonetic: "/tʃes/", unit: 5 },
  { id: "study", word: "study", meaning: "学习", phonetic: "/ˈstʌdi/", unit: 5 },
  { id: "basketball", word: "basketball", meaning: "篮球", phonetic: "/ˈbɑːskɪtbɔːl/", unit: 5 },
  { id: "activity", word: "activity", meaning: "活动", phonetic: "/ækˈtɪvɪti/", unit: 5 },

  // Unit 6 (46)
  { id: "apple", word: "apple", meaning: "苹果", phonetic: "/ˈæpəl/", unit: 6 },
  { id: "egg", word: "egg", meaning: "鸡蛋", phonetic: "/eɡ/", unit: 6 },
  { id: "bread", word: "bread", meaning: "面包", phonetic: "/bred/", unit: 6 },
  { id: "milk", word: "milk", meaning: "奶", phonetic: "/mɪlk/", unit: 6 },
  { id: "rice", word: "rice", meaning: "米饭", phonetic: "/raɪs/", unit: 6 },
  { id: "tomato", word: "tomato", meaning: "西红柿", phonetic: "/təˈmɑːtəʊ/", unit: 6 },
  { id: "juice", word: "juice", meaning: "果汁", phonetic: "/dʒuːs/", unit: 6 },
  { id: "candy", word: "candy", meaning: "糖果", phonetic: "/ˈkændi/", unit: 6 },
  { id: "ice_cream", word: "ice cream", meaning: "冰激凌", phonetic: "/ˌaɪs ˈkriːm/", unit: 6 },
  { id: "chicken", word: "chicken", meaning: "鸡肉", phonetic: "/ˈtʃɪkɪn/", unit: 6 },
  { id: "noodles", word: "noodles", meaning: "面条", phonetic: "/ˈnuːdəlz/", unit: 6 },
  { id: "banana", word: "banana", meaning: "香蕉", phonetic: "/bəˈnɑːnə/", unit: 6 },
  { id: "dinner", word: "dinner", meaning: "正餐", phonetic: "/ˈdɪnə/", unit: 6 },
  { id: "parent", word: "parent", meaning: "父母", phonetic: "/ˈpeərənt/", unit: 6 },
  { id: "dish", word: "dish", meaning: "一道菜", phonetic: "/dɪʃ/", unit: 6 },
  { id: "meat", word: "meat", meaning: "肉", phonetic: "/miːt/", unit: 6 },
  { id: "mushroom", word: "mushroom", meaning: "蘑菇", phonetic: "/ˈmʌʃruːm/", unit: 6 },
  { id: "potato", word: "potato", meaning: "土豆", phonetic: "/pəˈteɪtəʊ/", unit: 6 },
  { id: "eggplant", word: "eggplant", meaning: "茄子", phonetic: "/ˈeɡplɑːnt/", unit: 6 },
  { id: "food", word: "food", meaning: "食物", phonetic: "/fuːd/", unit: 6 },
  { id: "amazing", word: "amazing", meaning: "惊人的", phonetic: "/əˈmeɪzɪŋ/", unit: 6 },
  { id: "say", word: "say", meaning: "说", phonetic: "/seɪ/", unit: 6 },
  { id: "grape", word: "grape", meaning: "葡萄", phonetic: "/ɡreɪp/", unit: 6 },
  { id: "vegetable", word: "vegetable", meaning: "蔬菜", phonetic: "/ˈvedʒtəbəl/", unit: 6 },
  { id: "soup", word: "soup", meaning: "汤", phonetic: "/suːp/", unit: 6 },
  { id: "drink", word: "drink", meaning: "饮料", phonetic: "/drɪŋk/", unit: 6 },
  { id: "need", word: "need", meaning: "需要", phonetic: "/niːd/", unit: 6 },
  { id: "oil", word: "oil", meaning: "油", phonetic: "/ɔɪl/", unit: 6 },
  { id: "salt", word: "salt", meaning: "盐", phonetic: "/sɔːlt/", unit: 6 },
  { id: "beat", word: "beat", meaning: "搅拌", phonetic: "/biːt/", unit: 6 },
  { id: "dragon", word: "dragon", meaning: "龙", phonetic: "/ˈdræɡən/", unit: 6 },
  { id: "point", word: "point", meaning: "指", phonetic: "/pɔɪnt/", unit: 6 },
  { id: "house", word: "house", meaning: "房子", phonetic: "/haʊs/", unit: 6 },
  { id: "lot", word: "lot", meaning: "许多", phonetic: "/lɒt/", unit: 6 },
  { id: "cup", word: "cup", meaning: "杯子", phonetic: "/kʌp/", unit: 6 },
  { id: "real", word: "real", meaning: "真的", phonetic: "/rɪəl/", unit: 6 },
  { id: "picnic", word: "picnic", meaning: "野餐", phonetic: "/ˈpɪknɪk/", unit: 6 },
  { id: "sit", word: "sit", meaning: "坐", phonetic: "/sɪt/", unit: 6 },
  { id: "yummy", word: "yummy", meaning: "很好吃的", phonetic: "/ˈjʌmi/", unit: 6 },
  { id: "bottle", word: "bottle", meaning: "瓶子", phonetic: "/ˈbɒtəl/", unit: 6 },
  { id: "box", word: "box", meaning: "盒", phonetic: "/bɒks/", unit: 6 },
  { id: "peel", word: "peel", meaning: "外皮", phonetic: "/piːl/", unit: 6 },
  { id: "sure", word: "sure", meaning: "当然", phonetic: "/ʃʊə/", unit: 6 },
  { id: "minute", word: "minute", meaning: "分钟", phonetic: "/ˈmɪnɪt/", unit: 6 },
  { id: "sky", word: "sky", meaning: "天", phonetic: "/skaɪ/", unit: 6 },
  { id: "grass", word: "grass", meaning: "草", phonetic: "/ɡrɑːs/", unit: 6 },
]

// 辅助函数
export function getWordsByUnit(unit, grade = 3, semester = 2) {
  return WORDS.filter((w) => w.unit === unit && (w.grade || 3) === grade && (w.semester || 2) === semester)
}

export function getWordsByGradeSemester(grade, semester) {
  return WORDS.filter((w) => (w.grade || 3) === grade && (w.semester || 2) === semester)
}

export function getWordById(id) {
  return WORDS.find((w) => w.id === id) || null
}


