// 词库 — 210个单词，6个单元
export const WORDS = [
  // Unit 1 (27)
  { id: "feeling", word: "feeling", meaning: "感觉", unit: 1 },
  { id: "tired", word: "tired", meaning: "疲惫的", unit: 1 },
  { id: "sad", word: "sad", meaning: "难过的", unit: 1 },
  { id: "angry", word: "angry", meaning: "生气的", unit: 1 },
  { id: "scared", word: "scared", meaning: "害怕的", unit: 1 },
  { id: "cry", word: "cry", meaning: "哭", unit: 1 },
  { id: "laugh", word: "laugh", meaning: "笑", unit: 1 },
  { id: "stamp", word: "stamp", meaning: "剁(脚)", unit: 1 },
  { id: "sleep", word: "sleep", meaning: "睡觉", unit: 1 },
  { id: "new", word: "new", meaning: "新的", unit: 1 },
  { id: "game", word: "game", meaning: "游戏", unit: 1 },
  { id: "excited", word: "excited", meaning: "兴奋的", unit: 1 },
  { id: "sorry", word: "sorry", meaning: "对不起", unit: 1 },
  { id: "like", word: "like", meaning: "喜欢", unit: 1 },
  { id: "but", word: "but", meaning: "但是", unit: 1 },
  { id: "unhappy", word: "unhappy", meaning: "不开心的", unit: 1 },
  { id: "worried", word: "worried", meaning: "担心的", unit: 1 },
  { id: "not", word: "not", meaning: "不;不是", unit: 1 },
  { id: "feel", word: "feel", meaning: "感觉到", unit: 1 },
  { id: "find", word: "find", meaning: "找到", unit: 1 },
  { id: "doll", word: "doll", meaning: "玩偶", unit: 1 },
  { id: "football", word: "football", meaning: "足球", unit: 1 },
  { id: "eat", word: "eat", meaning: "吃", unit: 1 },
  { id: "his", word: "his", meaning: "他的", unit: 1 },
  { id: "cake", word: "cake", meaning: "蛋糕", unit: 1 },
  { id: "big", word: "big", meaning: "大的", unit: 1 },
  { id: "mouse", word: "mouse", meaning: "老鼠", unit: 1 },

  // Unit 2 (30)
  { id: "know", word: "know", meaning: "了解", unit: 2 },
  { id: "body", word: "body", meaning: "身体", unit: 2 },
  { id: "rock", word: "rock", meaning: "摇滚乐", unit: 2 },
  { id: "song", word: "song", meaning: "歌曲", unit: 2 },
  { id: "touch", word: "touch", meaning: "触摸", unit: 2 },
  { id: "head", word: "head", meaning: "头", unit: 2 },
  { id: "eye", word: "eye", meaning: "眼睛", unit: 2 },
  { id: "hair", word: "hair", meaning: "头发", unit: 2 },
  { id: "short", word: "short", meaning: "短的", unit: 2 },
  { id: "small", word: "small", meaning: "小的", unit: 2 },
  { id: "ear", word: "ear", meaning: "耳朵", unit: 2 },
  { id: "wave", word: "wave", meaning: "摆动", unit: 2 },
  { id: "leg", word: "leg", meaning: "腿", unit: 2 },
  { id: "foot", word: "foot", meaning: "脚", unit: 2 },
  { id: "nose", word: "nose", meaning: "鼻子", unit: 2 },
  { id: "face", word: "face", meaning: "脸", unit: 2 },
  { id: "arm", word: "arm", meaning: "手臂", unit: 2 },
  { id: "hand", word: "hand", meaning: "手", unit: 2 },
  { id: "mouth", word: "mouth", meaning: "嘴", unit: 2 },
  { id: "tooth", word: "tooth", meaning: "牙", unit: 2 },
  { id: "prize", word: "prize", meaning: "奖品", unit: 2 },
  { id: "bike", word: "bike", meaning: "自行车", unit: 2 },
  { id: "race", word: "race", meaning: "竞赛", unit: 2 },
  { id: "stretch", word: "stretch", meaning: "伸展", unit: 2 },
  { id: "shake", word: "shake", meaning: "摇动", unit: 2 },
  { id: "here", word: "here", meaning: "在这里", unit: 2 },
  { id: "Mr", word: "Mr", meaning: "先生", unit: 2 },
  { id: "back", word: "back", meaning: "回到原处", unit: 2 },
  { id: "worry", word: "worry", meaning: "担心", unit: 2 },
  { id: "robot", word: "robot", meaning: "机器人", unit: 2 },

  // Unit 3 (41)
  { id: "so", word: "so", meaning: "这么", unit: 3 },
  { id: "cool", word: "cool", meaning: "酷的", unit: 3 },
  { id: "clothes", word: "clothes", meaning: "衣服", unit: 3 },
  { id: "wear", word: "wear", meaning: "穿", unit: 3 },
  { id: "cap", word: "cap", meaning: "帽子", unit: 3 },
  { id: "T-shirt", word: "T-shirt", meaning: "T恤", unit: 3 },
  { id: "trousers", word: "trousers", meaning: "裤子", unit: 3 },
  { id: "sock", word: "sock", meaning: "袜子", unit: 3 },
  { id: "shiny", word: "shiny", meaning: "有光泽的", unit: 3 },
  { id: "shoe", word: "shoe", meaning: "鞋", unit: 3 },
  { id: "dress", word: "dress", meaning: "连衣裙", unit: 3 },
  { id: "sweater", word: "sweater", meaning: "毛线衣", unit: 3 },
  { id: "skirt", word: "skirt", meaning: "半身裙", unit: 3 },
  { id: "shirt", word: "shirt", meaning: "衬衫", unit: 3 },
  { id: "coat", word: "coat", meaning: "外套", unit: 3 },
  { id: "shorts", word: "shorts", meaning: "短裤", unit: 3 },
  { id: "king", word: "king", meaning: "国王", unit: 3 },
  { id: "want", word: "want", meaning: "想要", unit: 3 },
  { id: "beautiful", word: "beautiful", meaning: "美丽的", unit: 3 },
  { id: "make", word: "make", meaning: "做", unit: 3 },
  { id: "magic", word: "magic", meaning: "神奇的", unit: 3 },
  { id: "people", word: "people", meaning: "人", unit: 3 },
  { id: "them", word: "them", meaning: "它们", unit: 3 },
  { id: "after", word: "after", meaning: "在……后", unit: 3 },
  { id: "month", word: "month", meaning: "月", unit: 3 },
  { id: "try", word: "try", meaning: "试", unit: 3 },
  { id: "why", word: "why", meaning: "为什么", unit: 3 },
  { id: "wonderful", word: "wonderful", meaning: "令人惊叹的", unit: 3 },
  { id: "most", word: "most", meaning: "最", unit: 3 },
  { id: "any", word: "any", meaning: "其他的", unit: 3 },
  { id: "or", word: "or", meaning: "或", unit: 3 },
  { id: "fox", word: "fox", meaning: "狐狸", unit: 3 },
  { id: "monkey", word: "monkey", meaning: "猴子", unit: 3 },
  { id: "tell", word: "tell", meaning: "告诉", unit: 3 },
  { id: "truth", word: "truth", meaning: "真相", unit: 3 },
  { id: "wash", word: "wash", meaning: "洗", unit: 3 },
  { id: "hang", word: "hang", meaning: "悬挂", unit: 3 },
  { id: "hat", word: "hat", meaning: "帽子", unit: 3 },
  { id: "jeans", word: "jeans", meaning: "牛仔裤", unit: 3 },
  { id: "boot", word: "boot", meaning: "靴子", unit: 3 },
  { id: "robe", word: "robe", meaning: "长袍", unit: 3 },

  // Unit 4 (42)
  { id: "rain", word: "rain", meaning: "雨", unit: 4 },
  { id: "sun", word: "sun", meaning: "阳光", unit: 4 },
  { id: "rainy", word: "rainy", meaning: "多雨的", unit: 4 },
  { id: "run", word: "run", meaning: "跑", unit: 4 },
  { id: "windy", word: "windy", meaning: "多风的", unit: 4 },
  { id: "fly", word: "fly", meaning: "放飞", unit: 4 },
  { id: "kite", word: "kite", meaning: "风筝", unit: 4 },
  { id: "park", word: "park", meaning: "公园", unit: 4 },
  { id: "hot", word: "hot", meaning: "炎热的", unit: 4 },
  { id: "sunny", word: "sunny", meaning: "阳光充足的", unit: 4 },
  { id: "swim", word: "swim", meaning: "游泳", unit: 4 },
  { id: "water", word: "water", meaning: "水", unit: 4 },
  { id: "cold", word: "cold", meaning: "寒冷的", unit: 4 },
  { id: "snowy", word: "snowy", meaning: "多雪的", unit: 4 },
  { id: "throw", word: "throw", meaning: "投;扔", unit: 4 },
  { id: "snowball", word: "snowball", meaning: "雪球", unit: 4 },
  { id: "umbrella", word: "umbrella", meaning: "雨伞", unit: 4 },
  { id: "warm", word: "warm", meaning: "保暖的", unit: 4 },
  { id: "music", word: "music", meaning: "音乐", unit: 4 },
  { id: "weather", word: "weather", meaning: "天气", unit: 4 },
  { id: "bookshop", word: "bookshop", meaning: "书店", unit: 4 },
  { id: "wait", word: "wait", meaning: "等", unit: 4 },
  { id: "wet", word: "wet", meaning: "湿的", unit: 4 },
  { id: "again", word: "again", meaning: "又", unit: 4 },
  { id: "dry", word: "dry", meaning: "干燥的", unit: 4 },
  { id: "sell", word: "sell", meaning: "卖", unit: 4 },
  { id: "these", word: "these", meaning: "这些", unit: 4 },
  { id: "idea", word: "idea", meaning: "主意", unit: 4 },
  { id: "club", word: "club", meaning: "俱乐部", unit: 4 },
  { id: "welcome", word: "welcome", meaning: "欢迎", unit: 4 },
  { id: "stand", word: "stand", meaning: "站立", unit: 4 },
  { id: "board", word: "board", meaning: "公告牌", unit: 4 },
  { id: "walk", word: "walk", meaning: "走", unit: 4 },
  { id: "carefully", word: "carefully", meaning: "小心地", unit: 4 },
  { id: "tree", word: "tree", meaning: "树", unit: 4 },
  { id: "spring", word: "spring", meaning: "春天", unit: 4 },
  { id: "summer", word: "summer", meaning: "夏天", unit: 4 },
  { id: "autumn", word: "autumn", meaning: "秋天", unit: 4 },
  { id: "winter", word: "winter", meaning: "冬天", unit: 4 },
  { id: "season", word: "season", meaning: "季节", unit: 4 },
  { id: "drawing", word: "drawing", meaning: "图画", unit: 4 },
  { id: "cloudy", word: "cloudy", meaning: "多云的", unit: 4 },

  // Unit 5 (24)
  { id: "week", word: "week", meaning: "星期", unit: 5 },
  { id: "Monday", word: "Monday", meaning: "星期一", unit: 5 },
  { id: "Tuesday", word: "Tuesday", meaning: "星期二", unit: 5 },
  { id: "Wednesday", word: "Wednesday", meaning: "星期三", unit: 5 },
  { id: "Thursday", word: "Thursday", meaning: "星期四", unit: 5 },
  { id: "Friday", word: "Friday", meaning: "星期五", unit: 5 },
  { id: "Saturday", word: "Saturday", meaning: "星期六", unit: 5 },
  { id: "Sunday", word: "Sunday", meaning: "星期日", unit: 5 },
  { id: "before", word: "before", meaning: "在……以前", unit: 5 },
  { id: "room", word: "room", meaning: "房间", unit: 5 },
  { id: "close", word: "close", meaning: "关;闭合", unit: 5 },
  { id: "much", word: "much", meaning: "非常", unit: 5 },
  { id: "rabbit", word: "rabbit", meaning: "兔", unit: 5 },
  { id: "cat", word: "cat", meaning: "猫", unit: 5 },
  { id: "fish", word: "fish", meaning: "鱼", unit: 5 },
  { id: "busy", word: "busy", meaning: "忙碌的", unit: 5 },
  { id: "every", word: "every", meaning: "每一个", unit: 5 },
  { id: "cooking", word: "cooking", meaning: "做饭", unit: 5 },
  { id: "cook", word: "cook", meaning: "烹调", unit: 5 },
  { id: "Chinese", word: "Chinese", meaning: "中国的", unit: 5 },
  { id: "chess", word: "chess", meaning: "国际象棋", unit: 5 },
  { id: "study", word: "study", meaning: "学习", unit: 5 },
  { id: "basketball", word: "basketball", meaning: "篮球", unit: 5 },
  { id: "activity", word: "activity", meaning: "活动", unit: 5 },

  // Unit 6 (46)
  { id: "apple", word: "apple", meaning: "苹果", unit: 6 },
  { id: "egg", word: "egg", meaning: "鸡蛋", unit: 6 },
  { id: "bread", word: "bread", meaning: "面包", unit: 6 },
  { id: "milk", word: "milk", meaning: "奶", unit: 6 },
  { id: "rice", word: "rice", meaning: "米饭", unit: 6 },
  { id: "tomato", word: "tomato", meaning: "西红柿", unit: 6 },
  { id: "juice", word: "juice", meaning: "果汁", unit: 6 },
  { id: "candy", word: "candy", meaning: "糖果", unit: 6 },
  { id: "ice_cream", word: "ice cream", meaning: "冰激凌", unit: 6 },
  { id: "chicken", word: "chicken", meaning: "鸡肉", unit: 6 },
  { id: "noodles", word: "noodles", meaning: "面条", unit: 6 },
  { id: "banana", word: "banana", meaning: "香蕉", unit: 6 },
  { id: "dinner", word: "dinner", meaning: "正餐", unit: 6 },
  { id: "parent", word: "parent", meaning: "父母", unit: 6 },
  { id: "dish", word: "dish", meaning: "一道菜", unit: 6 },
  { id: "meat", word: "meat", meaning: "肉", unit: 6 },
  { id: "mushroom", word: "mushroom", meaning: "蘑菇", unit: 6 },
  { id: "potato", word: "potato", meaning: "土豆", unit: 6 },
  { id: "eggplant", word: "eggplant", meaning: "茄子", unit: 6 },
  { id: "food", word: "food", meaning: "食物", unit: 6 },
  { id: "amazing", word: "amazing", meaning: "惊人的", unit: 6 },
  { id: "say", word: "say", meaning: "说", unit: 6 },
  { id: "grape", word: "grape", meaning: "葡萄", unit: 6 },
  { id: "vegetable", word: "vegetable", meaning: "蔬菜", unit: 6 },
  { id: "soup", word: "soup", meaning: "汤", unit: 6 },
  { id: "drink", word: "drink", meaning: "饮料", unit: 6 },
  { id: "need", word: "need", meaning: "需要", unit: 6 },
  { id: "oil", word: "oil", meaning: "油", unit: 6 },
  { id: "salt", word: "salt", meaning: "盐", unit: 6 },
  { id: "beat", word: "beat", meaning: "搅拌", unit: 6 },
  { id: "dragon", word: "dragon", meaning: "龙", unit: 6 },
  { id: "point", word: "point", meaning: "指", unit: 6 },
  { id: "house", word: "house", meaning: "房子", unit: 6 },
  { id: "lot", word: "lot", meaning: "许多", unit: 6 },
  { id: "cup", word: "cup", meaning: "杯子", unit: 6 },
  { id: "real", word: "real", meaning: "真的", unit: 6 },
  { id: "picnic", word: "picnic", meaning: "野餐", unit: 6 },
  { id: "sit", word: "sit", meaning: "坐", unit: 6 },
  { id: "yummy", word: "yummy", meaning: "很好吃的", unit: 6 },
  { id: "bottle", word: "bottle", meaning: "瓶子", unit: 6 },
  { id: "box", word: "box", meaning: "盒", unit: 6 },
  { id: "peel", word: "peel", meaning: "外皮", unit: 6 },
  { id: "sure", word: "sure", meaning: "当然", unit: 6 },
  { id: "minute", word: "minute", meaning: "分钟", unit: 6 },
  { id: "sky", word: "sky", meaning: "天", unit: 6 },
  { id: "grass", word: "grass", meaning: "草", unit: 6 },
]

// 辅助函数
export function getWordsByUnit(unit) {
  return WORDS.filter((w) => w.unit === unit)
}

export function getWordById(id) {
  return WORDS.find((w) => w.id === id) || null
}

// 多学科扩展接口（架构预留）
export function getWordsBySubject(subject, grade, unit) {
  if (subject !== 'english') return []
  return getWordsByUnit(unit)
}

export function getUnitCount() {
  return 6
}


